=== pypi-data/pypi-mirror-78/packages/sila2lib/sila2lib-0.2.5-py3-none-any.whl/sila2lib/framework/schema/FeatureDefinition.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://www.sila-standard.org"
    targetNamespace="http://www.sila-standard.org">
  <xs:include schemaLocation="DataTypes.xsd"/>
  <xs:element name="Feature">
    <xs:complexType>
      <!-- Feature Content -->
      <xs:sequence>
        <xs:element type="tns:IdentifierType" name="Identifier" />
        <xs:element type="tns:DisplayNameType" name="DisplayName" />
        <xs:element type="xs:string" name="Description" />
        <!-- @Note: xs:all can not be used here, as it doesn't allow unbounded occurences -->
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Command" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element type="tns:SiLAElement" name="Parameter" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="Response" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="IntermediateResponse" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:DefinedExecutionErrorList" name="DefinedExecutionErrors" maxOccurs="1" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Property" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element type="tns:DataTypeType" name="DataType" />
                <xs:element type="tns:DefinedExecutionErrorList" name="DefinedExecutionErrors" maxOccurs="1" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Metadata" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element type="tns:DataTypeType" name="DataType" />
                <xs:element type="tns:DefinedExecutionErrorList" name="DefinedExecutionErrors" maxOccurs="1" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="DefinedExecutionError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element type="tns:SiLAElement" name="DataTypeDefinition" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
      </xs:sequence>

      <!-- Attributes -->
      <xs:attribute type="xs:string" name="Locale" use="optional" default="en-us" />
      <xs:attribute name="SiLA2Version" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="FeatureVersion" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="MaturityLevel" use="optional" default="Draft">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Draft" />
            <xs:enumeration value="Verified" />
            <xs:enumeration value="Normative" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Originator" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Category" use="optional" default="none">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="DefinedExecutionErrorList">
    <xs:sequence>
      <xs:element type="tns:IdentifierType" name="Identifier" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== pypi-data/pypi-mirror-78/packages/sila2lib/sila2lib-0.2.5-py3-none-any.whl/sila2lib/framework/feature_definitions/org.silastandard/CancelController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" MaturityLevel="Draft" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>CancelController</Identifier>
    <DisplayName>Cancel Controller</DisplayName>
    <Description>
        This feature cancel's any currently running command on the server
    </Description>
    <Command>
        <Identifier>Cancel</Identifier>
        <DisplayName>Cancel</DisplayName>
        <Description>
            Cancels all currently running commands on this server
        </Description>
        <Observable>No</Observable>
    </Command>
</Feature>

=== pypi-data/pypi-mirror-78/packages/sila2lib/sila2lib-0.2.5-py3-none-any.whl/sila2lib/framework/feature_definitions/org.silastandard/SimulationController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" MaturityLevel="Verified" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
  <Identifier>SimulationController</Identifier>
  <DisplayName>Simulation Controller</DisplayName>
  <Description>
    This Feature provides control over the simulation behaviour of a SiLA Server.

    A SiLA Server can run in two modes:
    (a) Real Mode - with real activities, e.g. addressing or controlling real hardware, e.g. through serial/CANBus commands,
        writing to real databases, moving real objects etc.
    (b) Simulation Mode - where every command is only simulated and responses are just example returns.

    Note that certain commands and properties might not be affected by this feature if they
    do not interact with the real world.
  </Description>
  <Command>
    <Identifier>StartSimulationMode</Identifier>
    <DisplayName>Start Simulation Mode</DisplayName>
    <Description>
      Sets the SiLA Server to run in Simulation Mode, i.e. all following commands are executed in simulation mode.

      The Simulation Mode can only be entered, if all hardware operations have been safely terminated
      or are in a controlled, safe state.

      The simulation mode can be stopped by issuing the 'Start Real Mode' command.
    </Description>
    <Observable>No</Observable>
    <DefinedExecutionErrors>
       <Identifier>StartSimulationModeFailed</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <Command>
    <Identifier>StartRealMode</Identifier>
    <DisplayName>Start Real Mode</DisplayName>
    <Description>
      Sets the SiLA Server to run in real mode, i.e. all following commands are executed with real-world
      interactions, like serial port/CAN communication, motor actions etc.

      If the server is in Simulation Mode it can be interrupted at any time. A re-initialization of
      the hardware might be required. The Real Mode can be stopped by issuing the 'Start Simulation Mode' command.
    </Description>
    <Observable>No</Observable>
    <DefinedExecutionErrors>
      <Identifier>StartRealModeFailed</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <Property>
    <Identifier>SimulationMode</Identifier>
    <DisplayName>SimulationMode</DisplayName>
    <Description>Indication whether SiLA Server is in Simulation Mode or not.</Description>
    <Observable>No</Observable>
    <DataType>
      <Basic>Boolean</Basic>
    </DataType>
  </Property>
  <DefinedExecutionError>
    <Identifier>StartSimulationModeFailed</Identifier>
    <DisplayName>The start of Simulation Mode failed.</DisplayName>
    <Description>
      The server cannot change to Simulation Mode.
      This error can, e.g., be thrown, if a real-world process needs to be ended before switching to simulation
      mode.
    </Description>
  </DefinedExecutionError>
  <DefinedExecutionError>
    <Identifier>StartRealModeFailed</Identifier>
    <DisplayName>The start of Real Mode failed.</DisplayName>
    <Description>
      The server cannot change to Real Mode.
      This error can, e.g., be thrown, if a device is not ready to change into Real Mode.
    </Description>
  </DefinedExecutionError>
</Feature>

=== pypi-data/pypi-mirror-78/packages/sila2lib/sila2lib-0.2.5-py3-none-any.whl/sila2lib/framework/feature_definitions/org.silastandard/LockController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" MaturityLevel="Verified" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
  <Identifier>LockController</Identifier>
  <DisplayName>Lock Controller</DisplayName>
  <Description>
    This Feature allows a SiLA Client to lock a SiLA Server for exclusive use, preventing other SiLA Clients
    from using the SiLA Server while it is locked. To lock a SiLA Server a Lock Identifier has to be set, using the
    'LockServer' command. This Lock Identifier has to be sent along with every (lock protected)
    request to the SiLA Server in order to use its functionality.

    To send the lock identifier the SiLA Client Meta Data 'LockIdentifier' has to be used.

    When locking a SiLA Server a timeout can be specified that defines the time after which the SiLA Server will
    be automatically unlocked if no request with a valid lock identifier has been received meanwhile.
    After the timeout has expired or after explicit unlock no lock identifier has to be sent any more.
  </Description>
  <Command>
    <Identifier>LockServer</Identifier>
    <DisplayName>Lock Server</DisplayName>
    <Description>
      Locks a SiLA Server for exclusive use by setting a lock identifier that has to be sent along with
      any following (lock protected) request as long as the SiLA Server is locked.
      The lock can be reset by issuing the 'Unlock Server' command.
    </Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>LockIdentifier</Identifier>
      <DisplayName>Lock Identifier</DisplayName>
      <Description>
        The lock identifier that has to be sent along with every (lock protected) request to use the server's
        functionality.
      </Description>
      <DataType>
        <Basic>String</Basic>
      </DataType>
    </Parameter>
    <Parameter>
      <Identifier>Timeout</Identifier>
      <DisplayName>Timeout</DisplayName>
      <Description>
        The time (in seconds) after a SiLA Server is automatically unlocked when no request with a valid lock identifier
        has been received meanwhile. A timeout of zero seconds specifies an infinite time (no timeout).
      </Description>
      <DataType>
        <Constrained>
          <DataType>
            <Basic>Integer</Basic>
          </DataType>
          <Constraints>
            <Unit>
              <Label>s</Label>
              <Factor>1</Factor>
              <Offset>0</Offset>
              <UnitComponent>
                <SIUnit>Second</SIUnit>
                <Exponent>1</Exponent>
              </UnitComponent>
            </Unit>
          </Constraints>
        </Constrained>
      </DataType>
    </Parameter>
    <DefinedExecutionErrors>
      <Identifier>ServerAlreadyLocked</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <Command>
    <Identifier>UnlockServer</Identifier>
    <DisplayName>Unlock Server</DisplayName>
    <Description>
      Unlocks a locked SiLA Server. No lock identifier has to be sent for any following calls until
      the server is locked again via the 'Lock Server' command.
    </Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>LockIdentifier</Identifier>
      <DisplayName>Lock Identifier</DisplayName>
      <Description>The lock identifier that has been used to lock the SiLA Server.</Description>
      <DataType>
        <Basic>String</Basic>
      </DataType>
    </Parameter>
    <DefinedExecutionErrors>
      <Identifier>ServerNotLocked</Identifier>
      <Identifier>InvalidLockIdentifier</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <Property>
    <Identifier>IsLocked</Identifier>
    <DisplayName>IsLocked</DisplayName>
    <Description>
      Returns true if the SiLA Server is currently locked or false else.

      This property MUST NOT be lock protected, so that any SiLA Client can query the current lock state
      of a SiLA Server.
    </Description>
    <Observable>No</Observable>
    <DataType>
      <Basic>Boolean</Basic>
    </DataType>
  </Property>
  <Metadata>
    <Identifier>LockIdentifier</Identifier>
    <DisplayName>Lock Identifier</DisplayName>
    <Description>
      The lock identifier has to be sent with every (lock protected) call in order to use the functionality
      of a locked SiLA Server.
    </Description>
    <DataType>
      <Basic>String</Basic>
    </DataType>
    <DefinedExecutionErrors>
      <Identifier>InvalidLockIdentifier</Identifier>
    </DefinedExecutionErrors>
  </Metadata>
  <DefinedExecutionError>
    <Identifier>InvalidLockIdentifier</Identifier>
    <DisplayName>Invalid Lock Identifier</DisplayName>
    <Description>The sent lock identifier is not valid.</Description>
  </DefinedExecutionError>
  <DefinedExecutionError>
    <Identifier>ServerAlreadyLocked</Identifier>
    <DisplayName>Server Already Locked</DisplayName>
    <Description>The SiLA Server can not be locked because it is already locked.</Description>
  </DefinedExecutionError>
  <DefinedExecutionError>
    <Identifier>ServerNotLocked</Identifier>
    <DisplayName>Server Not Locked</DisplayName>
    <Description>The SiLA Server can not be unlocked because it is not locked.</Description>
  </DefinedExecutionError>
</Feature>

=== pypi-data/pypi-mirror-78/packages/sila2lib/sila2lib-0.2.5-py3-none-any.whl/sila2lib/framework/feature_definitions/org.silastandard/ObservableCommandController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" MaturityLevel="Draft" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
  <Identifier>ObservableCommandController</Identifier>
  <DisplayName>Observable Command Controller</DisplayName>
  <Description>
    Allows to pause, resume or stop a currently running observable command
  </Description>
  <Command>
    <Identifier>Pause</Identifier>
    <DisplayName>Pause</DisplayName>
    <Description>Pause the command. The command can then be resumed again</Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>CommandExecutionUUID</Identifier>
      <DisplayName>Command Execution UUID</DisplayName>
      <Description>The observable command execution identifier</Description>
      <DataType>
        <DataTypeIdentifier>UUID</DataTypeIdentifier>
      </DataType>
    </Parameter>
    <DefinedExecutionErrors>
      <Identifier>InvalidCommandExecutionUUID</Identifier>
      <Identifier>InvalidCommandState</Identifier>
      <Identifier>OperationNotSupported</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <Command>
    <Identifier>Resume</Identifier>
    <DisplayName>Resume</DisplayName>
    <Description>Resume the command after it has been paused</Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>CommandExecutionUUID</Identifier>
      <DisplayName>Command Execution UUID</DisplayName>
      <Description>The observable command execution identifier</Description>
      <DataType>
        <DataTypeIdentifier>UUID</DataTypeIdentifier>
      </DataType>
    </Parameter>
    <DefinedExecutionErrors>
      <Identifier>InvalidCommandExecutionUUID</Identifier>
      <Identifier>InvalidCommandState</Identifier>
      <Identifier>OperationNotSupported</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <Command>
    <Identifier>Abort</Identifier>
    <DisplayName>Abort</DisplayName>
    <Description>Abort the command. This will make it impossible to resume the command</Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>CommandExecutionUUID</Identifier>
      <DisplayName>Command Execution UUID</DisplayName>
      <Description>The observable command execution identifier</Description>
      <DataType>
        <DataTypeIdentifier>UUID</DataTypeIdentifier>
      </DataType>
    </Parameter>
    <DefinedExecutionErrors>
      <Identifier>InvalidCommandExecutionUUID</Identifier>
      <Identifier>InvalidCommandState</Identifier>
      <Identifier>OperationNotSupported</Identifier>
    </DefinedExecutionErrors>
  </Command>
  <DefinedExecutionError>
    <Identifier>InvalidCommandExecutionUUID</Identifier>
    <DisplayName>Invalid Command Execution UUID</DisplayName>
    <Description>
      The specified command is not under execution
    </Description>
  </DefinedExecutionError>
  <DefinedExecutionError>
    <Identifier>InvalidCommandState</Identifier>
    <DisplayName>Invalid Command State</DisplayName>
    <Description>
      The specified command is not in a valid state to perform the operation (Pause, Resume or Abort)
    </Description>
  </DefinedExecutionError>
  <DefinedExecutionError>
    <Identifier>OperationNotSupported</Identifier>
    <DisplayName>Operation Not Supported</DisplayName>
    <Description>
      The operation (Pause, Resume or Abort) is not supported for the SiLA 2 command which the
      specified CommandExecutionUUID belongs to
    </Description>
  </DefinedExecutionError>
  <Property>
    <Identifier>SupportedCommands</Identifier>
    <DisplayName>Supported Commands</DisplayName>
    <Description>List of commands supported by this feature</Description>
    <Observable>No</Observable>
    <DataType>
      <List>
        <DataType>
          <Constrained>
            <DataType>
              <Basic>String</Basic>
            </DataType>
            <Constraints>
              <FullyQualifiedIdentifier>CommandIdentifier</FullyQualifiedIdentifier>
            </Constraints>
          </Constrained>
        </DataType>
      </List>
    </DataType>
  </Property>
  <DataTypeDefinition>
    <Identifier>UUID</Identifier>
    <DisplayName>UUID</DisplayName>
    <Description>A Universally Unique IDentifier (UUID) referring to observable command executions</Description>
    <DataType>
      <Constrained>
        <DataType>
          <Basic>String</Basic>
        </DataType>
        <Constraints>
          <Length>36</Length>
          <Pattern>[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{12}</Pattern>
        </Constraints>
      </Constrained>
    </DataType>
  </DataTypeDefinition>
</Feature>

=== pypi-data/pypi-mirror-78/packages/sila2lib/sila2lib-0.2.5-py3-none-any.whl/sila2lib/framework/feature_definitions/org.silastandard/AuthorizationService.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" MaturityLevel="Draft" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
  <Identifier>AuthorizationService</Identifier>
  <DisplayName>Authorization Service</DisplayName>
  <Description>
    This Feature provides access control for the implementing server.

    It specifies the SiLA Client Metadata for the access token, that has been provided by the
    AuthenticationService core Feature.
  </Description>
  <Metadata>
    <Identifier>AccessToken</Identifier>
    <DisplayName>AccessToken</DisplayName>
    <Description>Token to be sent with every call in order to get access to the SiLA Server functionality.</Description>
    <DataType>
      <Basic>String</Basic>
    </DataType>
    <DefinedExecutionErrors>
      <Identifier>InvalidAccessToken</Identifier>
    </DefinedExecutionErrors>
  </Metadata>
  <DefinedExecutionError>
    <Identifier>InvalidAccessToken</Identifier>
    <DisplayName>Invalid Access Token</DisplayName>
    <Description>The sent access token is not valid.</Description>
  </DefinedExecutionError>
</Feature>
