=== pypi-data/pypi-mirror-78/packages/pybill/pybill-1.2.0.tar.gz/pybill-1.2.0/pybill/xmlschema/pybill-config-1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:pbc="http://www.logilab.org/2010/PyBillConfig"
            targetNamespace="http://www.logilab.org/2010/PyBillConfig"
            elementFormDefault="qualified"
            attributeFormDefault="qualified">

  <xsd:element name="config">
    <xsd:complexType>
      <xsd:all>

	<!-- data of the company that emits the accounting documents -->
	<xsd:element ref="pbc:company"/>

	<!-- data of the bank where the bills must be paid -->
	<xsd:element ref="pbc:bank-data"/>

	<!-- lines of text inserted on pro-forma documents -->
	<xsd:element ref="pbc:agreement-intro"/>

	<!-- lines of text inserted in the footer -->
	<xsd:element ref="pbc:footer"/>

	<!-- specification of number separators -->
	<xsd:element ref="pbc:number-separators"/>

	<!-- localisation of words and phrases inserted in the documents -->
	<xsd:element ref="pbc:localisation"/>

      </xsd:all>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="format-version">
	<xsd:simpleType>
	  <xsd:restriction base="xsd:string">
	    <xsd:enumeration value="PBC-1.0"/> <!-- PyBill Configuration 1.0 -->
	  </xsd:restriction>
	</xsd:simpleType>
      </xsd:attribute>
    </xsd:complexType>
  </xsd:element>


  <!-- company data -->

  <xsd:element name="company">
    <xsd:complexType>
      <xsd:sequence>

        <xsd:element name="logo-file" type="xsd:string" minOccurs="0"/>

        <xsd:element name="orgname" type="xsd:string"/>

        <xsd:element name="address" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="street" type="xsd:string" 
                           minOccurs="0" maxOccurs="unbounded"/>
              <xsd:element name="pob" type="xsd:string" minOccurs="0"/>
              <xsd:element name="postcode" type="xsd:string" minOccurs="0"/>
              <xsd:element name="city" type="xsd:string" minOccurs="0"/>
              <xsd:element name="state" type="xsd:string" minOccurs="0"/>
              <xsd:element name="country" type="xsd:string" minOccurs="0"/>
              <xsd:element name="phone" type="xsd:string" minOccurs="0"/>
              <xsd:element name="fax" type="xsd:string" minOccurs="0"/>
              <xsd:element name="web" type="xsd:string" minOccurs="0"/>
              <xsd:element name="email" type="xsd:string" minOccurs="0"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>

      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <!-- bank data -->

  <xsd:element name="bank-data">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pbc:line" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <!-- agreement intro -->

  <xsd:element name="agreement-intro">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pbc:line" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <!-- footer -->

  <xsd:element name="footer">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="pbc:line" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <!-- line element used in the three previous ones -->

  <xsd:element name="line" type="xsd:string"/>


  <!-- specification of number separators -->

  <xsd:element name="number-separators">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="sign" type="xsd:string" minOccurs="0"/>
        <xsd:element name="thousands" type="xsd:string" minOccurs="0"/>
        <xsd:element name="digits" type="xsd:string" minOccurs="0"/>
      </xsd:all>
    </xsd:complexType>
  </xsd:element>


  <!-- localisation -->

  <xsd:element name="localisation">
    <xsd:complexType>
      <xsd:all>

        <xsd:element name="colon" type="xsd:string"/>
        <xsd:element name="phone-kw" type="xsd:string"/>
        <xsd:element name="fax-kw" type="xsd:string"/>
        <xsd:element name="web-kw" type="xsd:string"/>
        <xsd:element name="email-kw" type="xsd:string"/>

        <xsd:element name="doc-ref-kw" type="xsd:string"/>
        <xsd:element name="receiver-kw" type="xsd:string"/>
        <xsd:element name="sender-kw" type="xsd:string"/>
        <xsd:element name="on-date" type="xsd:string"/>

        <xsd:element name="bill" type="xsd:string"/>
        <xsd:element name="claim-form" type="xsd:string"/>
        <xsd:element name="downpayment" type="xsd:string"/>
        <xsd:element name="debit" type="xsd:string"/>
        <xsd:element name="pro-forma" type="xsd:string"/>

        <xsd:element name="number" type="xsd:string"/>
        <xsd:element name="dated" type="xsd:string"/>
        <xsd:element name="valid-until" type="xsd:string"/>

        <xsd:element name="intro-detail" type="xsd:string"/>

        <xsd:element name="quantity" type="xsd:string"/>
        <xsd:element name="description" type="xsd:string"/>
        <xsd:element name="vat-rate" type="xsd:string"/>
        <xsd:element name="unit-price" type="xsd:string"/>
        <xsd:element name="tf-unit-price" type="xsd:string"/>
        <xsd:element name="price" type="xsd:string"/>
        <xsd:element name="tf-price" type="xsd:string"/>
        <xsd:element name="it-price" type="xsd:string"/>
        <xsd:element name="holdback-on" type="xsd:string"/>
        <xsd:element name="ita-est" type="xsd:string"/>

        <xsd:element name="total" type="xsd:string"/>
        <xsd:element name="tf-total" type="xsd:string"/>
        <xsd:element name="vat-amount" type="xsd:string"/>
        <xsd:element name="it-total" type="xsd:string"/>
        <xsd:element name="including" type="xsd:string"/>
        <xsd:element name="holdback" type="xsd:string"/>
        <xsd:element name="on-tf" type="xsd:string"/>
        <xsd:element name="on-vat" type="xsd:string"/>

        <xsd:element name="debit-total" type="xsd:string"/>
        <xsd:element name="charged-downpayment" type="xsd:string"/>
        <xsd:element name="charged-on" type="xsd:string"/>
        <xsd:element name="issued-debit" type="xsd:string"/>
        <xsd:element name="issued-on" type="xsd:string"/>
        <xsd:element name="to-be-paid" type="xsd:string"/>

        <xsd:element name="payment-terms" type="xsd:string"/>

        <xsd:element name="to-bring-forward" type="xsd:string"/>
        <xsd:element name="carry-forward" type="xsd:string"/>

        <!-- For backward compatibility with older formats (PyBill 0.X) -->
        <xsd:element name="your-ref-kw" type="xsd:string" minOccurs="0"/>
        <xsd:element name="purch-ref-kw" type="xsd:string" minOccurs="0"/>
        <xsd:element name="supplier-ref-kw" type="xsd:string" minOccurs="0"/>

       </xsd:all>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== pypi-data/pypi-mirror-78/packages/pybill/pybill-1.2.0.tar.gz/pybill-1.2.0/pybill/configs/default.xml
<?xml version="1.0" encoding="UTF-8"?>

<pbc:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.logilab.org/2010/PyBillConfig
                                http://www.logilab.org/xmlschemas/pybill/pybill-config-1_0.xsd"
            xmlns:pbc="http://www.logilab.org/2010/PyBillConfig"
            pbc:name="Default configuration"
            pbc:format-version="PBC-1.0">
 <pbc:company>
  <!-- <pbc:logo-file></pbc:logo-file> -->
  <pbc:orgname>Not Defined &lt;orgname&gt;</pbc:orgname>
  <pbc:address>
   <pbc:street>Not Defined &lt;street&gt;</pbc:street>
   <!-- <pbc:postcode></pbc:postcode> -->
   <pbc:city>Not Defined &lt;city&gt;</pbc:city>
  </pbc:address>
 </pbc:company>

 <pbc:bank-data>
  <pbc:line>Not Defined &lt;bank data&gt;</pbc:line>
 </pbc:bank-data>

 <pbc:agreement-intro>
  <pbc:line>(name and title of the signatory)</pbc:line>
  <pbc:line>(the hand-written phrase</pbc:line>
  <pbc:line>"agreed on"+date</pbc:line>
  <pbc:line>should precede the signature)</pbc:line>
 </pbc:agreement-intro>

 <pbc:footer>
  <!-- <pbc:line></pbc:line> -->
 </pbc:footer>

 <pbc:number-separators>
  <pbc:sign></pbc:sign>
  <pbc:thousands>,</pbc:thousands>
  <pbc:digits>.</pbc:digits>
 </pbc:number-separators>

 <pbc:localisation>
  <pbc:colon>:</pbc:colon>
  <pbc:phone-kw>Phone</pbc:phone-kw>
  <pbc:fax-kw>Fax</pbc:fax-kw>
  <pbc:web-kw>Web</pbc:web-kw>
  <pbc:email-kw>Email</pbc:email-kw>
  <pbc:doc-ref-kw>Our ref</pbc:doc-ref-kw>
  <pbc:receiver-kw>Attn</pbc:receiver-kw>
  <pbc:sender-kw>Contact</pbc:sender-kw>
  <pbc:on-date>on</pbc:on-date>
  <pbc:bill>Bill</pbc:bill>
  <pbc:claim-form>Claim Form</pbc:claim-form>
  <pbc:debit>Debit</pbc:debit>
  <pbc:downpayment>Downpayment</pbc:downpayment>
  <pbc:pro-forma>Purchase Order</pbc:pro-forma>
  <pbc:number># </pbc:number>
  <pbc:dated>dated</pbc:dated>
  <pbc:valid-until>valid until</pbc:valid-until>
  <pbc:intro-detail>All the amounts are displayed in Euros.</pbc:intro-detail>
  <pbc:quantity>Qty</pbc:quantity>
  <pbc:description>Description</pbc:description>
  <pbc:vat-rate>VAT Rate</pbc:vat-rate>
  <pbc:unit-price>Unit Price</pbc:unit-price>
  <pbc:tf-unit-price>TF Unit Price</pbc:tf-unit-price>
  <pbc:price>Price</pbc:price>
  <pbc:tf-price>TF Price</pbc:tf-price>
  <pbc:it-price>IT Price</pbc:it-price>
  <pbc:holdback-on>Holdback on</pbc:holdback-on>
  <pbc:ita-est>i.e.</pbc:ita-est>
  <pbc:total>Total</pbc:total>
  <pbc:tf-total>TF Total</pbc:tf-total>
  <pbc:vat-amount>VAT</pbc:vat-amount>
  <pbc:it-total>IT Total</pbc:it-total>
  <pbc:including>including</pbc:including>
  <pbc:holdback>Holdback</pbc:holdback>
  <pbc:on-tf>on TF amounts</pbc:on-tf>
  <pbc:on-vat>on VAT amounts</pbc:on-vat>
  <pbc:debit-total>Total of debit (EUR)</pbc:debit-total>
  <pbc:charged-downpayment>Downpayment</pbc:charged-downpayment>
  <pbc:charged-on>charged on</pbc:charged-on>
  <pbc:issued-debit>Debit</pbc:issued-debit>
  <pbc:issued-on>issued on</pbc:issued-on>
  <pbc:to-be-paid>To be paid (EUR)</pbc:to-be-paid>
  <pbc:payment-terms>Payment Terms</pbc:payment-terms>
  <pbc:to-bring-forward>To bring forward</pbc:to-bring-forward>
  <pbc:carry-forward>Carry forward</pbc:carry-forward>
  <!-- Kept for compatibility with 0.X version of PyBill -->
  <pbc:your-ref-kw>Your ref</pbc:your-ref-kw>
  <pbc:purch-ref-kw>Purchase</pbc:purch-ref-kw>
  <pbc:supplier-ref-kw>Supplier</pbc:supplier-ref-kw>
 </pbc:localisation>

</pbc:config>

=== pypi-data/pypi-mirror-78/packages/pybill/pybill-1.2.0.tar.gz/pybill-1.2.0/pybill/examples/configs/config-fr.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<pbc:config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.logilab.org/2010/PyBillConfig
                                ../../xmlschema/pybill-config-1_0.xsd"
            xmlns:pbc="http://www.logilab.org/2010/PyBillConfig"
            pbc:name="Exemple de fichier de config (Français)"
            pbc:format-version="PBC-1.0">
 <pbc:company>
  <!-- Should be an absolute path to the logo. Here, we hack the following
       definition in ``genexamples.py`` -->
  <pbc:logo-file>../logos/mpe.png</pbc:logo-file>
  <pbc:orgname>MaPetiteEntreprise</pbc:orgname>
  <pbc:address>
   <pbc:street>1, Allée Louya</pbc:street>
   <pbc:pob>BP 1</pbc:pob>
   <pbc:postcode>F-75001</pbc:postcode>
   <pbc:city>PARIS</pbc:city>
   <pbc:phone>(+33) 1 23 45 67 89</pbc:phone>
   <pbc:fax>(+33) 1 23 45 67 89</pbc:fax>
   <pbc:web>www.mpe.fr</pbc:web>
   <pbc:email>contact@mpe.fr</pbc:email>
  </pbc:address>
 </pbc:company>

 <pbc:bank-data>
  <pbc:line>Banque de l'Écureuil Doré</pbc:line>
  <pbc:line>IBAN: FR01 2345 6789 0123 4567 8901 234</pbc:line>
 </pbc:bank-data>

 <pbc:agreement-intro>
  <pbc:line>(lieu et date, nom et qualité du signataire)</pbc:line>
  <pbc:line>(faire précéder la signature de</pbc:line>
  <pbc:line>la mention manuscrite "bon pour accord")</pbc:line>
 </pbc:agreement-intro>

 <pbc:footer>
  <pbc:line>MaPetiteEntreprise&#xA0;- Société au capital de 37 000 Euros</pbc:line>
  <pbc:line>Siège Social&#xA0;: 1, Allée Louya&#xA0;- F75001 PARIS</pbc:line>
 </pbc:footer>

 <pbc:number-separators>
  <pbc:sign> </pbc:sign>
  <pbc:thousands>.</pbc:thousands>
  <pbc:digits>,</pbc:digits>
 </pbc:number-separators>

 <pbc:localisation>
  <pbc:colon> :</pbc:colon>
  <pbc:phone-kw>Tél</pbc:phone-kw>
  <pbc:fax-kw>Fax</pbc:fax-kw>
  <pbc:web-kw>Web</pbc:web-kw>
  <pbc:email-kw>Adel</pbc:email-kw>
  <pbc:doc-ref-kw>N/Réf</pbc:doc-ref-kw>
  <pbc:receiver-kw>À l'attention de</pbc:receiver-kw>
  <pbc:sender-kw>Affaire suivie par</pbc:sender-kw>
  <pbc:on-date>le</pbc:on-date>
  <pbc:bill>Facture</pbc:bill>
  <pbc:claim-form>Note de Frais</pbc:claim-form>
  <pbc:debit>Avoir</pbc:debit>
  <pbc:downpayment>Acompte</pbc:downpayment>
  <pbc:pro-forma>Bon de Commande</pbc:pro-forma>
  <pbc:number>n°</pbc:number>
  <pbc:dated>en date du</pbc:dated>
  <pbc:valid-until>valide jusqu'au</pbc:valid-until>
  <pbc:intro-detail>Sauf mention contraire, tous les montants sont portés en Euros.</pbc:intro-detail>
  <pbc:quantity>Qté</pbc:quantity>
  <pbc:description>Désignation</pbc:description>
  <pbc:vat-rate>Taux TVA</pbc:vat-rate>
  <pbc:unit-price>Prix unit.</pbc:unit-price>
  <pbc:tf-unit-price>Prix unit. HT</pbc:tf-unit-price>
  <pbc:price>Prix</pbc:price>
  <pbc:tf-price>Prix HT</pbc:tf-price>
  <pbc:it-price>Prix TTC</pbc:it-price>
  <pbc:holdback-on>Retenue de garantie sur</pbc:holdback-on>
  <pbc:ita-est>soit</pbc:ita-est>
  <pbc:total>Total</pbc:total>
  <pbc:tf-total>Total HT</pbc:tf-total>
  <pbc:vat-amount>TVA</pbc:vat-amount>
  <pbc:it-total>Total TTC</pbc:it-total>
  <pbc:including>dont</pbc:including>
  <pbc:holdback>Retenue de garantie</pbc:holdback>
  <pbc:on-tf>sur montants HT</pbc:on-tf> 
  <pbc:on-vat>sur montants TVA</pbc:on-vat>
  <pbc:debit-total>Total Avoir</pbc:debit-total>
  <pbc:charged-downpayment>Acompte</pbc:charged-downpayment>
  <pbc:charged-on>facturé le</pbc:charged-on>
  <pbc:issued-debit>Avoir</pbc:issued-debit>
  <pbc:issued-on>émis le</pbc:issued-on>
  <pbc:to-be-paid>À payer</pbc:to-be-paid>
  <pbc:payment-terms>Conditions de règlement</pbc:payment-terms>
  <pbc:to-bring-forward>À reporter</pbc:to-bring-forward>
  <pbc:carry-forward>Report</pbc:carry-forward>
  <!-- Conservé pour la compatibilité avec la version 0.X de PyBill -->
  <pbc:your-ref-kw>V/Réf</pbc:your-ref-kw>
  <pbc:purch-ref-kw>Commande</pbc:purch-ref-kw>
  <pbc:supplier-ref-kw>Fournisseur</pbc:supplier-ref-kw>
 </pbc:localisation>

</pbc:config>
